# Use to cache dependencies, basically, so rebuilding docker doesn't
# take forever.
FROM haskell:8.10

WORKDIR /opt/example
COPY . /opt/example

# FIXME: version pinning, e.g., package-foo=1.3.*
RUN apt-get update && apt-get install -y zlib1g-dev libpq-dev libjwt-dev nginx certbot python3-certbot-nginx cron && rm -rf /var/lib/apt/lists/*

RUN cabal update && cabal build

# We won't run cron unless user passes SSL flag? or should we do self sign flag...?
RUN echo "0 12 * * * /usr/bin/certbot renew --quiet" >> /etc/crontab

# startup script
# NOTE: would it be better to put this in the actual regular Dockerfile?
RUN mv /opt/example/docker/web-startup.sh /usr/local/bin/startup.sh
RUN chmod 777 /usr/local/bin/startup.sh