version: '3.8'
services:
  web:
    depends_on:
      - db
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "80:8080"
      - "8080:80"
    environment:
      - SCOTTY_ENV
      - SCOTTY_SITE_TITLE
      - SCOTTY_DATABASE_URL
    # if test then use local mount, otherwise use volume?
    volumes:
      # this is for changing to localmount! ro
      #- ${DEV_VOLUME_STATIC}
      # See readme about this line below.
      - built:/opt/example/built
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
  built:
    driver: local