# Use to cache dependencies, basically, so rebuilding docker doesn't
# take forever.
FROM haskell:8.10

WORKDIR /opt/example
COPY . /opt/example

# FIXME: version pinning, e.g., package-foo=1.3.*
RUN apt-get update && apt-get install -y zlib1g-dev libpq-dev libjwt-dev nginx && rm -rf /var/lib/apt/lists/*

RUN cabal update && cabal build

# startup script
RUN mv /opt/example/docker/web-startup.sh /usr/local/bin/startup.sh
RUN chmod 777 /usr/local/bin/startup.sh